# =============================================================================
# 02_descriptive.R - survey-weighted descriptive analysis
# =============================================================================
source("R/functions.R")
primary <- readRDS("data_processed/primary_h217_analysis.rds")

des <- svydesign(ids = ~VARPSU, strata = ~VARSTR, weights = ~weight,
                 nest = TRUE, data = primary)

# Core weighted outcomes
mean_y1 <- coef(svymean(~y1_exp, des, na.rm = TRUE))[1]
mean_y2 <- coef(svymean(~y2_exp, des, na.rm = TRUE))[1]
zero_y1 <- coef(
  svymean(~I(as.numeric(y1_exp == 0)), des, na.rm = TRUE)
)[1]

zero_y2 <- coef(
  svymean(~I(as.numeric(y2_exp == 0)), des, na.rm = TRUE)
)[1]

q_y2 <- weighted_quantile(primary$y2_exp, primary$weight, c(.5,.75,.9,.95,.99))

# Concentration shares: proportion of total expenditure generated by top p% people
concentration_share <- function(y, w, top_p) {
  d <- tibble(y=y,w=w) |> filter(is.finite(y), is.finite(w), w>0) |> arrange(desc(y)) |>
    mutate(pop_share=cumsum(w)/sum(w), spend=y*w)
  selected <- d$pop_share <= top_p
  if (!any(selected)) selected[1] <- TRUE
  sum(d$spend[selected]) / sum(d$spend)
}

conc <- tibble(
  top_group = c("Top 1%","Top 5%","Top 10%"),
  spending_share = c(concentration_share(primary$y2_exp, primary$weight,.01),
                     concentration_share(primary$y2_exp, primary$weight,.05),
                     concentration_share(primary$y2_exp, primary$weight,.10))
)
write_csv(conc, "results/tables/spending_concentration.csv")

# Persistence of high cost using weighted 95th percentile in each year
thr1 <- weighted_quantile(primary$y1_exp, primary$weight, .95)
thr2 <- weighted_quantile(primary$y2_exp, primary$weight, .95)
primary <- primary |> mutate(high_y1 = y1_exp >= thr1, high_y2 = y2_exp >= thr2)
persistence <- primary |>
  group_by(high_y1) |>
  summarise(weighted_prob_high_y2 = weighted_mean(high_y2, weight), n=n(), .groups="drop")
write_csv(persistence, "results/tables/high_cost_persistence.csv")

summary_tbl <- tibble(
  statistic = c("Weighted mean Year-1 expenditure","Weighted mean Year-2 expenditure",
                "Weighted zero-spending fraction Year 1","Weighted zero-spending fraction Year 2",
                "Weighted median Year-2 expenditure","Weighted 95th percentile Year-2 expenditure"),
  value = c(mean_y1,mean_y2,zero_y1,zero_y2,q_y2[1],q_y2[4])
)
write_csv(summary_tbl, "results/tables/descriptive_summary.csv")

# Figures
p1 <- ggplot(primary, aes(y2_exp, weight = weight)) +
  geom_histogram(bins = 80) + scale_x_log10(labels = scales::dollar) +
  labs(title = "Year-2 healthcare expenditure (log x-scale)", x = "Expenditure", y = "Weighted count") +
  theme_minimal()
ggsave("results/figures/y2_expenditure_distribution.png", p1, width=8, height=5, dpi=300)

p2 <- ggplot(primary, aes(x = factor(high_y1), fill = factor(high_y2), weight = weight)) +
  geom_bar(position = "fill") +
  labs(title="Persistence of high-cost status", x="High cost in Year 1", y="Weighted proportion", fill="High cost Year 2") +
  theme_minimal()
ggsave("results/figures/high_cost_persistence.png", p2, width=7, height=5, dpi=300)
